apiVersion: v1
kind: Service
metadata:
  name: transcoder
  namespace: stube
  labels:
    app: transcoder
spec:
  type: ClusterIP
  selector:
    app: transcoder
  ports:
    - name: http
      port: 80
      targetPort: 8080
