apiVersion: v1
kind: ServiceAccount
metadata:
  name: transcoder
  namespace: stube
  labels:
    app: transcoder
    value-stream: stube
# Link your registry pull secret to this ServiceAccount if the image is
# hosted in a private registry.
